# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HelloCli < Formula
  desc ""
  homepage ""
  version "0.1.3"

  on_macos do
    on_intel do
      url "https://github.com/hassaku63/hello-cli/releases/download/v0.1.3/hello-cli_Darwin_x86_64.tar.gz"
      sha256 "431c8a0bc9992d4278c4766d1f4a400cc1519fba743c750a91c7a8ef17efaee3"

      def install
        bin.install "hello"
      end
    end
    on_arm do
      url "https://github.com/hassaku63/hello-cli/releases/download/v0.1.3/hello-cli_Darwin_arm64.tar.gz"
      sha256 "03fa919b81c40afeb46e23d5ddc19c34f2e85d13f9cdfe91e4f39d9eb64ec044"

      def install
        bin.install "hello"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hassaku63/hello-cli/releases/download/v0.1.3/hello-cli_Linux_x86_64.tar.gz"
        sha256 "6c9dfe95084d85096429e3fb037cc31a8aa40d123ee88116957f65590ed04cc4"

        def install
          bin.install "hello"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hassaku63/hello-cli/releases/download/v0.1.3/hello-cli_Linux_arm64.tar.gz"
        sha256 "1b81de868b3b6fd8a3931d08b2e98aac86b9438fbb41a429132268d49d9ae4a5"

        def install
          bin.install "hello"
        end
      end
    end
  end
end
